const Application = require('../models/Application');

// 1️⃣ SUBMIT A NEW APPLICATION
const submitApplication = async (req, res) => {
    try {
        const { jobId, jobRole, company, coverLetter, userEmail } = req.body;

        // 🎯 CRITICAL CHECK: Verify if the file was successfully caught by Multer middleware
        if (!req.file) {
            return res.status(400).json({ success: false, error: "CV file upload is required!" });
        }

        // The filename generated by Multer (e.g., 17185343846-928374.pdf)
        const cvFilename = req.file.filename;

        const newApplication = new Application({
            jobId,
            jobRole,
            company,
            coverLetter,
            cv: cvFilename, // Saving the unique server filename into the MongoDB 'cv' field
            userEmail
        });

        const savedApplication = await newApplication.save();

        res.status(201).json({
            success: true,
            message: "Application submitted successfully to NextGen Database! 🎉",
            data: savedApplication
        });
    } catch (error) {
        console.error("Error saving application: ", error);
        res.status(500).json({ success: false, error: "Failed to save application to database", details: error.message });
    }
};

// 2️⃣ GET APPLICATIONS (FILTER BY EMAIL OR FETCH ALL)
const getApplications = async (req, res) => {
    try {
        const companyName = req.query.company; // Query parameter (e.g., ?company=NextGen)
        let applications;

        if (companyName) {
            // Fetch applications that belong to the specific company name
            applications = await Application.find({ company: companyName });
        } else {
            // Fetch all applications if no company filter is provided
            applications = await Application.find();
        }

        res.json(applications);
    } catch (error) {
        console.error("Error fetching applications: ", error);
        res.status(500).json({ success: false, error: "Failed to fetch applications from database" });
    }
};

// 3️⃣ UPDATE APPLICATION STATUS (SHORTLIST / REJECT)
const updateApplicationStatus = async (req, res) => {
    try {
        const { id } = req.params;
        const { status } = req.body;

        // Validation to check if status is provided in request body
        if (!status) {
            return res.status(400).json({ success: false, error: "Status field is required" });
        }

        // Find database document by ID and apply updates
        const updatedApplication = await Application.findByIdAndUpdate(
            id,
            { status },
            { new: true, runValidators: true }
        );

        // Error boundary if document does not exist
        if (!updatedApplication) {
            return res.status(404).json({ success: false, error: "Application record not found" });
        }

        res.status(200).json({
            success: true,
            message: "Application status updated successfully directly in database!",
            application: updatedApplication
        });
    } catch (error) {
        console.error("Error updating application status: ", error);
        res.status(500).json({ success: false, error: "Failed to update application status", details: error });
    }
};

// Exporting all operational methods safely
module.exports = {
    submitApplication,
    getApplications,
    updateApplicationStatus
};