const Application = require('../models/Application');

// 1️⃣ SUBMIT A NEW APPLICATION
const submitApplication = async (req, res) => {
    try {
        const { jobId, jobRole, company, coverLetter, userEmail } = req.body;

        // Verify if the CV file was successfully uploaded via Multer middleware
        if (!req.file) {
            return res.status(400).json({ success: false, error: "CV file upload is required!" });
        }

        // Get the unique filename generated by Multer
        const cvFilename = req.file.filename;

        const newApplication = new Application({
            jobId,
            jobRole,
            company: company || 'NextGen',
            coverLetter,
            cv: cvFilename,
            userEmail
        });

        const savedApplication = await newApplication.save();

        res.status(201).json({
            success: true,
            message: "Application submitted successfully to NextGen Database! 🎉",
            data: savedApplication
        });
    } catch (error) {
        console.error("Error saving application: ", error);
        res.status(500).json({ success: false, error: "Failed to save application to database", details: error.message });
    }
};

// 2️⃣ GET APPLICATIONS (SUPPORT FILTERING BY COMPANY OR USER EMAIL)
const getApplications = async (req, res) => {
    try {
        const companyName = req.query.company; 
        const userEmail = req.query.userEmail; 

        let applications;

        if (companyName) {
            // Filter applications by specific company name
            applications = await Application.find({ company: companyName });
        } else if (userEmail) {
            // Filter applications by applicant's email address
            applications = await Application.find({ userEmail: userEmail });
        } else {
            // Fetch all applications if no filters are provided
            applications = await Application.find();
        }

        res.json(applications);
    } catch (error) {
        console.error("Error fetching applications: ", error);
        res.status(500).json({ success: false, error: "Failed to fetch applications from database" });
    }
};

// 3️⃣ UPDATE APPLICATION STATUS (SHORTLIST / REJECT)
const updateApplicationStatus = async (req, res) => {
    try {
        const { id } = req.params;
        const { status } = req.body;

        if (!status) {
            return res.status(400).json({ success: false, error: "Status field is required" });
        }

        const updatedApplication = await Application.findByIdAndUpdate(
            id,
            { status },
            { new: true, runValidators: true }
        );

        if (!updatedApplication) {
            return res.status(404).json({ success: false, error: "Application record not found" });
        }

        res.status(200).json({
            success: true,
            message: "Application status updated successfully directly in database!",
            application: updatedApplication
        });
    } catch (error) {
        console.error("Error updating application status: ", error);
        res.status(500).json({ success: false, error: "Failed to update application status", details: error });
    }
};

// 4️⃣ SCHEDULE INTERVIEW (EMPLOYER ACTION)
const scheduleInterview = async (req, res) => {
    const { id } = req.params;
    const { meetingLink, interviewDate, interviewTime } = req.body; 

    try {
        const updatedApplication = await Application.findByIdAndUpdate(
            id,
            {
                status: 'Interview Scheduled',    
                zoomLink: meetingLink,            
                interviewDate: interviewDate,     
                interviewTime: interviewTime      
            },
            { new: true } 
        );

        if (!updatedApplication) {
            return res.status(404).json({ message: "Target application not found in the NextGen database." });
        }

        res.status(200).json({ success: true, data: updatedApplication });

    } catch (error) {
        console.error("NextGen Server Error: Failed to schedule interview -", error);
        res.status(500).json({ message: "Internal server error while updating interview details.", error });
    }
};

module.exports = {
    submitApplication,
    getApplications,
    updateApplicationStatus,
    scheduleInterview
};